spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hiberbate:
        #show_sql: true 시스템 아웃으로 출력됨 -> 사용 지양
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug #로거를 통해서 출력하는게 좋음
